BACKMATTER = \
	backmatter-intro.tex \
	list-of-abbreviations.tex \
	bibliography.tex \
	eidesstattliche-erklaerung.tex \
	backmatter-outro.tex

_backmatter.tex: $(BACKMATTER)
	cat $(BACKMATTER) > ../$@

.PHONY: clean-intermediary

clean-intermediary:
	echo 'Nothing to clean-intermediary in backmatter.'
