# Sequence is important here:
LCHEPS = \
	lch-eps-intro.tex \
	xyl-growth.tex \
	xyl-hcs.tex \
	inh-tol.tex \
	lch-tol.tex \
	inh-hcs.tex \
	strain.tex \
	lch-pf.tex \
	discussion.tex \
	outlook.tex

_lch-eps.tex: $(LCHEPS)
	cat $(LCHEPS) > ../$@

.PHONY: clean-intermediary

clean-intermediary:
	echo 'Nothing to clean-intermediary in lch-eps.'
