# Sequence is important here:
FUNPF = \
	intro.tex \
	fun-pf.tex \
	outlook.tex

_fun-pf.tex: $(FUNPF)
	cat $(FUNPF) > ../$@

.PHONY: clean-intermediary

clean-intermediary:
	echo 'Nothing to clean-intermediary in fun-pf.'
