TITLEPAGE = \
	titlepage_intro.tex \
	titlepage.tex

_titlepage.tex: $(TITLEPAGE)
	cat $(TITLEPAGE) > ../$@

.PHONY: clean-intermediary _titlepage.tex

clean-intermediary:
	echo 'Nothing to clean-intermediary in titlepage.'
