# Sequence is important here:
AGARSMEDIA = agars-media-intro.tex \
	ph-adjust.tex \
	ama.tex \
	jfm.tex \
	lb.tex \
	sm.tex \
	yepd.tex \
	tes.tex \
	vitamins.tex \
	agar.tex \
	fungi-plates.tex

_agars-media.tex: $(AGARSMEDIA)
	cat $(AGARSMEDIA) > ../$@

.PHONY: clean-intermediary

clean-intermediary:
	echo 'Nothing to clean-intermediary in agars-media.'
