# Sequence is important here:
SUPPLEMENTS = \
	supplements-intro.tex \
	m-and-m-supp.tex \
	lch-eps-supp.tex \
	fun-pf-supp.tex

_supplements.tex: $(SUPPLEMENTS)
	cat $(SUPPLEMENTS) > ../$@

.PHONY: clean-intermediary

clean-intermediary:
	echo 'Nothing to clean-intermediary in supplements.'
